CREATE DATABASE cft;

USE cft;

CREATE TABLE CLIENTS
(
    ID INT CONSTRAINT CLIENTS_PK PRIMARY KEY IDENTITY,
	NAME VARCHAR(1000),
	PLACE_OF_BIRTH VARCHAR(1000),
	DATE_OF_BIRTH  DATE,
	ADDRESS VARCHAR(1000),
	PASSPORT VARCHAR(100) UNIQUE
);

CREATE TABLE TARIFS
(
    ID INT CONSTRAINT TARIFS_PK PRIMARY KEY IDENTITY,
	NAME VARCHAR(100) UNIQUE,
	COST  DECIMAL(10,2)
);

CREATE TABLE PRODUCTYPE
(
    ID INT CONSTRAINT PRODUCT_TYPE_PK PRIMARY KEY IDENTITY,
	NAME VARCHAR(100),
	BEGIN_DATE  DATE,
	CLOSE_DATE DATE,
	TARIF_REF INT,
	CONSTRAINT PROD_TYPE_TAR_FK FOREIGN KEY (TARIF_REF) REFERENCES TARIFS(ID)
);

CREATE TABLE PRODUCTS
(
    ID INT CONSTRAINT PRODUCTS_PK PRIMARY KEY IDENTITY,
	PRODUCT_TYPE_ID INT,
	NAME VARCHAR(100),
	CLIENT_REF INT,
	OPEN_DATE DATE,
	CLOSE_DATE DATE,
	CONSTRAINT PROD_CL_FK FOREIGN KEY (CLIENT_REF) REFERENCES CLIENTS(ID),
	CONSTRAINT PROD_PRODTYPE_FK FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCTYPE(ID),
);


CREATE TABLE ACCOUNTS
(
    ID INT CONSTRAINT ACCOUNTS_PK PRIMARY KEY IDENTITY,
	NAME VARCHAR(100),
	SALDO DECIMAL(10,2),
	CLIENT_REF INT,
	OPEN_DATE DATE,
	CLOSE_DATE DATE,
	PRODUCT_REF INT,
	ACC_NUM VARCHAR(25) UNIQUE,
	CONSTRAINT ACC_CL_FK FOREIGN KEY (CLIENT_REF) REFERENCES CLIENTS(ID),
	CONSTRAINT ACC_PROD_FK FOREIGN KEY (PRODUCT_REF) REFERENCES PRODUCTS(ID)
);

CREATE TABLE RECORDS
(
    ID INT CONSTRAINT RECORDS_PK PRIMARY KEY IDENTITY,
	DT INT CHECK(DT>=0 AND DT<=1),
	SUM DECIMAL(10,2),
	ACC_REF INT,
	OPER_DATE  DATE,
	CONSTRAINT REC_ACC_FK FOREIGN KEY (ACC_REF) REFERENCES ACCOUNTS(ID)
);


